In [1]:
"""
SPDX-License-Identifier: GPL-3.0-or-later
© 2008-2025 San Diego State University Research Foundation (SDSURF).
See LICENSE file or https://www.gnu.org/licenses/gpl-3.0.html for details. 

@file gradient.cpp
@brief Mimetic Gradient Operator Class
@date 2025/06/01
"""

'\nSPDX-License-Identifier: GPL-3.0-or-later\n© 2008-2025 San Diego State University Research Foundation (SDSURF).\nSee LICENSE file or https://www.gnu.org/licenses/gpl-3.0.html for details. \n\n@file gradient.cpp\n@brief Mimetic Gradient Operator Class\n@date 2025/06/01\n'

In [2]:
import numpy as np
from scipy.sparse import csr_array

In [24]:
class Gradient:
    def __init__(self, k, m, dx):

        assert (k % 2) == 0, "k must be even"
        assert 1 < k < 9, "valid range of k is [1,9]"
        assert m >= 2 * k, "m must be greater or equal to 2k"

        self.k =  k
        self.m = m
        self.dx = dx
        
        match k:
            case 2:
                row0 = np.array([-8.0 / 3.0, 3.0, -1.0 / 3.0])
                data = np.concatenate([
                    row0,
                    -1.0 * row0[::-1]                    
                    ])
                row = np.concatenate([
                    np.zeros(k+1), 
                    np.full(k+1, m)
                    ]).astype(int)
                col = np.concatenate([
                    np.arange(k+1),
                    np.arange(m-1,m+2)
                    ])
                
                DATAM =  np.array([-1.0, 1.0])
                dataM = np.array([])
                rowM = np.array([])
                colM = np.array([])
                for i in range(1, m):
                    rowM = np.append(rowM, np.full(k,i)).astype(int)
                    colM = np.append(colM, np.arange(i,i+2)).astype(int)
                    dataM = np.append(dataM, DATAM)

                offset = len(row0)
                data = np.insert(data, offset, dataM)
                row = np.insert(row, offset, rowM)
                col = np.insert(col, offset, colM)

                # Weights
                P = [ 3.0 / 8.0 , 9.0 / 8.0 , 1.0 , 9.0 / 8.0 , 3.0 / 8.0 ]

            case 4:
                row0 = np.array([-352.0 / 105.0, 35.0 / 8.0, -35.0 / 24.0, 21.0 / 40.0, -5.0 / 56.0])
                row1 = np.array([ 16.0 / 105.0, -31.0 / 24.0, 29.0 / 24.0, -3.0 / 40.0, 1.0 / 168.0])
                data = np.concatenate([
                    row0,
                    row1,
                    -1.0 * row1[::-1],
                    -1.0 * row0[::-1]                    
                    ])
                row = np.concatenate([
                    np.zeros(k+1), 
                    np.full(k+1, 1),
                    np.full(k+1, m-1),
                    np.full(k+1, m)
                    ]).astype(int)
                col = np.concatenate([
                    np.arange(k+1),
                    np.arange(k+1), 
                    np.arange(m-3,m+2),
                    np.arange(m-3,m+2)
                    ])
                DATAM =  np.array([1.0 / 24.0, -9.0 / 8.0, 9.0 / 8.0, -1.0 / 24.0])
                dataM = np.array([])
                rowM = np.array([])
                colM = np.array([])
                for i in range(2, m - 1):
                    rowM = np.append(rowM, np.full(k,i)).astype(int)
                    colM = np.append(colM, np.arange(i-1,i+3)).astype(int)
                    dataM = np.append(dataM, DATAM)

                offset = len(row0)+len(row1)
                data = np.insert(data, offset, dataM)
                row = np.insert(row, offset, rowM)
                col = np.insert(col, offset, colM)

                P = [ 1606.0 / 4535.0 , 941.0 / 766.0 , 1384.0 / 1541.0 , 1371.0 / 1346.0, 
                     701.0 / 700.0 , 1371.0 / 1346.0 , 1384.0 / 1541.0 , 941.0 / 766.0, 
                     1606.0 / 4535.0 ]
            
            case 6:
                '''`
                A = [-13016/3465  693/128  -385/128 693/320 -495/448  385/1152 -63/1408; ...
                    496/3465 -811/640   449/384 -29/960  -11/448   13/1152 -37/21120; ...
                     -8/385   179/1920 -153/128 381/320 -101/1344   1/128   -3/7040];
                '''
                row0 = np.array([-13016/3465,  693/128,  -385/128, 693/320, -495/448,  385/1152, -63/1408])
                row1 = np.array([496/3465, -811/640,   449/384, -29/960,  -11/448,   13/1152, -37/21120])
                row2 = np.array([-8/385,   179/1920, -153/128, 381/320, -101/1344,   1/128,   -3/7040])
                data = np.concatenate([
                    row0,
                    row1,
                    row2,
                    -1.0 * row2[::-1],
                    -1.0 * row1[::-1],
                    -1.0 * row0[::-1]                    
                    ])
                print(np.reshape(data/ self.dx,(6,7)))
                row = np.concatenate([
                    np.zeros(k+1), 
                    np.full(k+1, 1),
                    np.full(k+1, 2),
                    np.full(k+1, m-2),
                    np.full(k+1, m-1),
                    np.full(k+1, m)
                    ]).astype(int)
                col = np.concatenate([
                    np.arange(k+1),
                    np.arange(k+1), 
                    np.arange(k+1),
                    np.arange(m-k+1,m+2),
                    np.arange(m-k+1,m+2),
                    np.arange(m-k+1,m+2)
                    ])
                
                #print(row)
                #print(col)
                #print(row.size)
                #print(col.size)

                DATAM =  np.array([-3/640, 25/384, -75/64, 75/64, -25/384, 3/640])
                dataM = np.array([])
                rowM = np.array([])
                colM = np.array([])
                for i in range(3, m - 2):
                    rowM = np.append(rowM, np.full(k,i)).astype(int)
                    colM = np.append(colM, np.arange(i-2,i+4)).astype(int)
                    dataM = np.append(dataM, DATAM)

                offset = len(row0)+len(row1)+len(row2)
                data = np.insert(data, offset, dataM)
                row = np.insert(row, offset, rowM)
                col = np.insert(col, offset, colM)
                #print(row)
                #print(col)
                #print(row.size)
                #print(col.size)
            case _:
                raise ValueError(f"Unsupported value of k: {k}")


        self.G = csr_array((data, (row, col)), dtype=np.float64) / self.dx

    def toarray(self):
        return self.G.toarray()



In [4]:
k = 2
m = 2*k+1
dx = 1/m
G = Gradient(k, m, dx)
np.set_printoptions(linewidth=160) 
G.toarray()

array([[-13.33333333,  15.        ,  -1.66666667,   0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,  -5.        ,   5.        ,   0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,  -5.        ,   5.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,  -5.        ,   5.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,  -5.        ,   5.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,   1.66666667, -15.        ,  13.33333333]])

In [5]:
k = 4
m = 2*k+1
dx = 1/m
G = Gradient(k, m, dx)
np.set_printoptions(linewidth=256) 
G.toarray()

array([[-30.17142857,  39.375     , -13.125     ,   4.725     ,  -0.80357143,   0.        ,   0.        ,   0.        ,   0.        ,   0.        ,   0.        ],
       [  1.37142857, -11.625     ,  10.875     ,  -0.675     ,   0.05357143,   0.        ,   0.        ,   0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.375     , -10.125     ,  10.125     ,  -0.375     ,   0.        ,   0.        ,   0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.375     , -10.125     ,  10.125     ,  -0.375     ,   0.        ,   0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.375     , -10.125     ,  10.125     ,  -0.375     ,   0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,   0.375     , -10.125     ,  10.125     ,  -0.375     ,   0.        ,   0.        ,   0.        ],
       [  0.        , 

In [25]:
k = 6
m = 2*k+1
dx = 1/m
G = Gradient(k, m, dx)
np.set_printoptions(linewidth=512) 
G.toarray()

[[-4.88334776e+01  7.03828125e+01 -3.91015625e+01  2.81531250e+01 -1.43638393e+01  4.34461806e+00 -5.81676136e-01]
 [ 1.86089466e+00 -1.64734375e+01  1.52005208e+01 -3.92708333e-01 -3.19196429e-01  1.46701389e-01 -2.27746212e-02]
 [-2.70129870e-01  1.21197917e+00 -1.55390625e+01  1.54781250e+01 -9.76934524e-01  1.01562500e-01 -5.53977273e-03]
 [ 5.53977273e-03 -1.01562500e-01  9.76934524e-01 -1.54781250e+01  1.55390625e+01 -1.21197917e+00  2.70129870e-01]
 [ 2.27746212e-02 -1.46701389e-01  3.19196429e-01  3.92708333e-01 -1.52005208e+01  1.64734375e+01 -1.86089466e+00]
 [ 5.81676136e-01 -4.34461806e+00  1.43638393e+01 -2.81531250e+01  3.91015625e+01 -7.03828125e+01  4.88334776e+01]]


array([[-4.88334776e+01,  7.03828125e+01, -3.91015625e+01,  2.81531250e+01, -1.43638393e+01,  4.34461806e+00, -5.81676136e-01,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.86089466e+00, -1.64734375e+01,  1.52005208e+01, -3.92708333e-01, -3.19196429e-01,  1.46701389e-01, -2.27746212e-02,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.70129870e-01,  1.21197917e+00, -1.55390625e+01,  1.54781250e+01, -9.76934524e-01,  1.01562500e-01, -5.53977273e-03,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -6.09375000e-02,  8.46354167e-01, -1.52343750e+01,  1.52343750e+01, -8.46354167e-01,  6.09375000e-02,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+

In [7]:
G_tb = np.array([
  [-48.8335,   70.3828,  -39.1016,   28.1531,  -14.3638,    4.3446,   -0.5817,         0,         0,         0,         0,         0,         0,         0,         0],
  [  1.8609,  -16.4734,   15.2005,   -0.3927,   -0.3192,    0.1467,   -0.0228,         0,         0,         0,         0,         0,         0,         0,         0],
  [ -0.2701,    1.2120,  -15.5391,   15.4781,   -0.9769,    0.1016,   -0.0055,         0,         0,         0,         0,         0,         0,         0,         0],
  [       0,   -0.0609,    0.8464,  -15.2344,   15.2344,   -0.8464,    0.0609,         0,         0,         0,         0,         0,         0,         0,         0],
  [       0,         0,   -0.0609,    0.8464,  -15.2344,   15.2344,   -0.8464,    0.0609,         0,         0,         0,         0,         0,         0,         0],
  [       0,         0,         0,   -0.0609,    0.8464,  -15.2344,   15.2344,   -0.8464,    0.0609,         0,         0,         0,         0,         0,         0],
  [       0,         0,         0,         0,   -0.0609,    0.8464,  -15.2344,   15.2344,   -0.8464,    0.0609,         0,         0,         0,         0,         0],
  [       0,         0,         0,         0,         0,   -0.0609,    0.8464,  -15.2344,   15.2344,   -0.8464,    0.0609,         0,         0,         0,         0],
  [       0,         0,         0,         0,         0,         0,   -0.0609,    0.8464,  -15.2344,   15.2344,   -0.8464,    0.0609,         0,         0,         0],
  [       0,         0,         0,         0,         0,         0,         0,   -0.0609,    0.8464,  -15.2344,   15.2344,   -0.8464,    0.0609,         0,         0],
  [       0,         0,         0,         0,         0,         0,         0,         0,   -0.0609,    0.8464,  -15.2344,   15.2344,   -0.8464,    0.0609,         0],
  [       0,         0,         0,         0,         0,         0,         0,         0,    0.0055,   -0.1016,    0.9769,  -15.4781,   15.5391,   -1.2120,    0.2701],
  [       0,         0,         0,         0,         0,         0,         0,         0,    0.0228,   -0.1467,    0.3192,    0.3927,  -15.2005,   16.4734,   -1.8609],
  [       0,         0,         0,         0,         0,         0,         0,         0,    0.5817,   -4.3446,   14.3638,  -28.1531,   39.1016,  -70.3828,   48.8335]])

In [38]:
print(f'||G-G_tb||={format(np.linalg.norm(G.toarray()-G_tb), ".2e")}')

||G-G_tb||=3.11e-04


In [ ]:
ks=[2,4,6]
tol = 1e-10
for k in ks:
    m = 2*k+1
    dx=1/m
    G= Gradient(k,m,dx)

[[-4.88334776e+01  7.03828125e+01 -3.91015625e+01  2.81531250e+01 -1.43638393e+01  4.34461806e+00 -5.81676136e-01]
 [ 1.86089466e+00 -1.64734375e+01  1.52005208e+01 -3.92708333e-01 -3.19196429e-01  1.46701389e-01 -2.27746212e-02]
 [-2.70129870e-01  1.21197917e+00 -1.55390625e+01  1.54781250e+01 -9.76934524e-01  1.01562500e-01 -5.53977273e-03]
 [ 5.53977273e-03 -1.01562500e-01  9.76934524e-01 -1.54781250e+01  1.55390625e+01 -1.21197917e+00  2.70129870e-01]
 [ 2.27746212e-02 -1.46701389e-01  3.19196429e-01  3.92708333e-01 -1.52005208e+01  1.64734375e+01 -1.86089466e+00]
 [ 5.81676136e-01 -4.34461806e+00  1.43638393e+01 -2.81531250e+01  3.91015625e+01 -7.03828125e+01  4.88334776e+01]]


ValueError: Unsupported value of k: 8